// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DepCheck
{
    internal sealed partial class Vsix
    {
        public const string Id = "DepCheck.7cbfef69-d736-4b8b-97d6-2ff2addd44f2";
        public const string Name = "OWASP Dependency Check";
        public const string Description = @"Checks current project for CVE";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
